services:
    phil_e_taylor_doctrine_encrypt.orm_subscriber:
        class: Philetaylor\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%phil_e_taylor_doctrine_encrypt.encryptor_class_name%", "%phil_e_taylor_doctrine_encrypt.keys%"]
        tags:
            -  { name: doctrine.event_subscriber }

    Philetaylor\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber:
        alias: phil_e_taylor_doctrine_encrypt.orm_subscriber

    phil_e_taylor_doctrine_encrypt.subscriber:
        alias: phil_e_taylor_doctrine_encrypt.orm_subscriber

    phil_e_taylor_doctrine_encrypt.encryptor:
        class: Philetaylor\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%phil_e_taylor_doctrine_encrypt.encryptor_class_name%"
            - "%phil_e_taylor_doctrine_encrypt.keys%"